{{- if .Values.sonataFlowOperator.enabled }}
  {{- $unmanagedNamespaceExists := include "unmanaged-resource-exists" (list "v1" "Namespace" "" .Values.sonataFlowOperator.subscription.namespace .Release.Name .Capabilities.APIVersions) }}
  {{- if and (eq $unmanagedNamespaceExists "false") .Values.sonataFlowOperator.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sonataFlowOperator.subscription.namespace }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless-logic
  namespace: {{ .Values.sonataFlowOperator.subscription.namespace }}
spec: {}
---
{{- end }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.sonataFlowOperator.subscription.name }}
  namespace: {{ .Values.sonataFlowOperator.subscription.namespace }}
spec:
  channel: {{ .Values.sonataFlowOperator.subscription.channel }}
  installPlanApproval: {{ .Values.sonataFlowOperator.subscription.installPlanApproval }}
  name: {{ .Values.sonataFlowOperator.subscription.name }}
  source: {{ .Values.sonataFlowOperator.subscription.sourceName }}
  sourceNamespace: openshift-marketplace
  {{- if ne .Values.sonataFlowOperator.subscription.startingCSV "" }}
  startingCSV: {{ .Values.sonataFlowOperator.subscription.startingCSV }}
  {{- end }}
{{- end }}
