sonataFlowOperator:
  isReleaseCandidate: true # Indicates RC builds should be used by the chart to install Sonataflow
  enabled: true # whether the operator should be deployed by the chart
  subscription:
    namespace: openshift-serverless-logic # namespace where the operator should be deployed
    channel: alpha # channel of an operator package to subscribe to
    name: logic-operator-rhel8 # name of the operator package
    sourceName: sonataflow-brew # name of the catalog source
    startingCSV: logic-operator-rhel8.v1.33.0 # The initial version of the operator

rhdhOperator:
  isReleaseCandidate: true # Indicates RC builds should be used by the chart to install RHDH
  enabled: true # whether the operator should be deployed by the chart
  subscription:
    namespace: rhdh-operator # namespace where the operator should be deployed
    channel: fast # channel of an operator package to subscribe to
    name: rhdh # name of the operator package
    sourceName: rhdh-brew # name of the catalog source
    startingCSV: rhdh-operator.v1.2.0 # The initial version of the operator

sonataflow:
  images:
    4.13: brew.registry.redhat.io/rh-osbs/iib:747442
    4.14: brew.registry.redhat.io/rh-osbs/iib:747447
    4.15: brew.registry.redhat.io/rh-osbs/iib:747453
    4.16: brew.registry.redhat.io/rh-osbs/iib:747466

rhdh:
  images:
    4.13: quay.io/rhdh/iib:1.2.0.RC-06-18-v4.13-x86_64
    4.14: quay.io/rhdh/iib:1.2.0.RC-06-18-v4.14-x86_64
    4.15: quay.io/rhdh/iib:1.2.0.RC-06-18-v4.15-x86_64
    4.16: quay.io/rhdh/iib:1.2.0.RC-06-18-v4.16-x86_64
