isReleaseCandidate: true # Indicates RC builds should be used by the chart to install RHDH and Sonataflow
ocpVersion: v4.15 # The version of the target OCP cluster. Supported versions are: v4.13, v4.14, v4.15, v4.16

sonataFlowOperator:
  enabled: true # whether the operator should be deployed by the chart
  subscription:
    namespace: openshift-serverless-logic # namespace where the operator should be deployed
    channel: alpha # channel of an operator package to subscribe to
    installPlanApproval: Automatic # whether the update should be installed automatically
    name: logic-operator-rhel8 # name of the operator package
    sourceName: sonataflow-brew # name of the catalog source
    startingCSV: logic-operator-rhel8.v1.33.0 # The initial version of the operator

rhdhOperator:
  enabled: true # whether the operator should be deployed by the chart
  subscription:
    namespace: rhdh-operator # namespace where the operator should be deployed
    channel: fast # channel of an operator package to subscribe to
    installPlanApproval: Automatic # whether the update should be installed automatically
    name: rhdh # name of the operator package
    sourceName: rhdh-brew # name of the catalog source
    startingCSV: rhdh-operator.v1.2.0 # The initial version of the operator
